{{- if not .Values.s3LocalEnabled -}}
# Convert this to a SealedSecret using kubeseal and replace it here
apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: remote-auth-config
stringData:
  AWS_ACCESS_KEY_ID: "123"
  AWS_SECRET_ACCESS_KEY: "456"
{{- end -}}